services:
  - type: web
    name: kokoro-fastapi
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    region: oregon
    branch: master
    envVars:
      - key: PYTHONPATH
        value: /app:/app/api
      - key: USE_GPU
        value: "false"
      - key: DEVICE
        value: "cpu"
      - key: DOWNLOAD_MODEL
        value: "true"
      - key: PHONEMIZER_ESPEAK_PATH
        value: /usr/bin
      - key: PHONEMIZER_ESPEAK_DATA
        value: /usr/share/espeak-ng-data
      - key: ESPEAK_DATA_PATH
        value: /usr/share/espeak-ng-data
      - key: ONNX_NUM_THREADS
        value: "2"
      - key: ONNX_INTER_OP_THREADS
        value: "1"
      - key: ONNX_EXECUTION_MODE
        value: "parallel"
      - key: ONNX_OPTIMIZATION_LEVEL
        value: "all"
    healthCheckPath: /health
    autoDeploy: true
