services:
  - type: web
    name: kokoro-fastapi
    env: docker
    dockerfilePath: ./Dockerfile.production
    plan: free
    envVars:
      - key: PYTHONPATH
        value: /app:/app/api
      - key: USE_GPU
        value: "false"
      - key: DEVICE
        value: "cpu"
      - key: DOWNLOAD_MODEL
        value: "true"
      - key: PHONEMIZER_ESPEAK_PATH
        value: /usr/bin
      - key: PHONEMIZER_ESPEAK_DATA
        value: /usr/share/espeak-ng-data
      - key: ESPEAK_DATA_PATH
        value: /usr/share/espeak-ng-data
    healthCheckPath: /health
