services:
  - type: web
    name: kokoro-tts
    env: python
    region: singapore
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
      mkdir -p /opt/render/project/api/src/models/v1_0
      mkdir -p /opt/render/project/api/src/voices/v1_0
      mkdir -p /tmp/kokoro_temp
    startCommand: python -m uvicorn api.src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: USE_GPU
        value: false
      - key: DEVICE
        value: cpu
      - key: DOWNLOAD_MODEL
        value: true
      - key: PHONEMIZER_ESPEAK_PATH
        value: /usr/bin
      - key: PHONEMIZER_ESPEAK_DATA
        value: /usr/share/espeak-ng-data
      - key: ESPEAK_DATA_PATH
        value: /usr/share/espeak-ng-data
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: MODEL_DIR
        value: /opt/render/project/api/src/models/v1_0
      - key: VOICES_DIR
        value: /opt/render/project/api/src/voices/v1_0
      - key: TEMP_FILE_DIR
        value: /tmp/kokoro_temp